name: chesspro_app
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon-foreground.png"
  adaptive_icon_background: "assets/icon-background.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
  - assets/logo-light.svg
  - assets/logo-dark.svg
  - assets/mode-pvp.svg
  - assets/mode-pvb.svg
  - assets/mode-bvb.svg
