name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: run backend server
        run: |
          cd app_backend
          cp ~/env-variables/.env-backend ./.env
          npm install
          pm2 restart app-backend
        
      - name: run websocket server
        run : |
          cd ../websocket_server
          cp ~/env-variables/.env-websocket ./.env
          npm install
          pm2 restart websocket-server
